### PR TITLE
Increase modeleditor tests coverage

### PR DESCRIPTION
**Pull request by jamiebull1**
Adds tests for untested parts of modeleditor.py and fixes an  IDF import bug #81.

### CODE REVIEW

**Comment by jamiebull1** [comment]
As well as the conflict, this fails on python 3 for a filename passed as a bytestring so I've marked it as work in progress.

**Comment by jamiebull1** [comment]
Ok, the tests are passing on python 3 now (turned out to be because the path to the resources folder is different from p3) and the conflicts are fixed. Coverage in modeleditor is now up to 94%.

**Comment by jamiebull1** [comment]
@santoshphilip This is tested and ready to go if you want it.

**Comment by jamiebull1** [comment]
Back to WIP pending changes mentioned in #81

**Comment by jamiebull1** [comment]
@santoshphilip Ok, no more IO in these tests so I think it's ready to merge now. I had to add the ability to take a file handle to the main `save()` for the sake of testing. This doesn't exactly play well with the fact that `saveas` also changes the `idfname`, since it gets renamed as the StringIO object (though it is immediately thrown away when the test finishes). 

It may be worth adding a warning to the user if they try to pass something that isn't a string to either `saveas` or `savecopy`. The documentation is clear that the function requires a `str` though so I think the intended usage is clear enough. What do you think?

**Comment by santoshphilip** [comment]
Jamie,
    Your changes are in branch `jamiebull1-modeleditor_tests`
I did the following:
- All pytests pass in python2
- took steps to test python3 code:
    - deleted the python code in folder ./eppy/p3
    - ran sh 2to3sh.sh.sh in ./eppy/eppy
    - ran python3 tests in folder p3
    - python3 test fail

I did not look deeply into the failure. May be an easy fix. Could you take a look ?

Santosh

**Comment by jamiebull1** [comment]
@santoshphilip It was string/bytes encoding and comparison issues in the tests. Fixed now.

**Comment by santoshphilip** [comment]
The python3 test pass.
I'll look at the diffs and then merge into devlop

**Comment by santoshphilip** [comment]
this has been merged into develop

**Pull request merged**
