### PR TITLE
I98 thermal properties

### PR DESCRIPTION
**Pull request by jamiebull1**
Tests are passing. Comments welcome.

#98

### CODE REVIEW

**Comment by santoshphilip** [comment]
I'll look thru over the weekend.
If all looks good will merge it back into `i102_zonesurfaces`.
I still need to do a few more things in `i102_zonesurfaces`

**Comment by santoshphilip** [comment]
I did a code review. It looks good.
I am going to merge it into branch `i102_zonesurfaces ` and then continue to work on that branch

It would be good to have another pair of eyes peer-review the physics of the calc. 
Peer-review just the file `eppy/constructions/thermal_properties.py`. One of the points of being open source is to have more eyeballs looking at the code :-)

for ease of review, I have pasted the code below:

    INSIDE_FILM_R = 0.12
    OUTSIDE_FILM_R = 0.03


    def rvalue(ddtt):
        """thickness (m) / conductivity (W/m-K)
        """
        if ddtt.obj[0] == 'Material':
            thickness = ddtt.obj[ddtt.objls.index('Thickness')]
            conductivity = ddtt.obj[ddtt.objls.index('Conductivity')]
            rvalue = thickness / conductivity
        else:
            rvalue = INSIDE_FILM_R + OUTSIDE_FILM_R
            layers = ddtt.obj[2:]
            rvalue += sum(ddtt.theidf.getobject('MATERIAL', l).rvalue 
                          for l in layers)
        return rvalue

    def uvalue(ddtt):
        """reciprocal of the r value (W/K)
        """
        return 1 / rvalue(ddtt)

    def heatcapacity(ddtt):
        """thickness (m) * density (kg/m3) * specific heat (J/kg-K) * 0.001
        """
        if ddtt.obj[0] == 'Material':
            thickness = ddtt.obj[ddtt.objls.index('Thickness')]
            density = ddtt.obj[ddtt.objls.index('Density')]
            specificheat = ddtt.obj[ddtt.objls.index('Specific_Heat')]
            heatcapacity = thickness * density * specificheat * 0.001
        else:
            layers = ddtt.obj[2:]
            heatcapacity = sum(ddtt.theidf.getobject('MATERIAL', l).heatcapacity 
                          for l in layers)
        return heatcapacity
 
@JasonGlazer can you take a quick look

**Comment by crollinjones** [comment]
Just to confirm - the inside and outside film R-values are added to the construction R-value, not each individual material R-value. I am not a pythonista so I am not sure if I am reading the code correctly.

**Comment by santoshphilip** [comment]
The code is doing it correctly - adding the film values to the construction R-Value. 

The code you are looking at is:

    rvalue = INSIDE_FILM_R + OUTSIDE_FILM_R
    layers = ddtt.obj[2:]
    rvalue += sum(ddtt.theidf.getobject('MATERIAL', l).rvalue 
                  for l in layers)


If the code was written more explicitly, it would look like this:

    film_rvalue = INSIDE_FILM_R + OUTSIDE_FILM_R
    layers = ddtt.obj[2:]
    mat_rvalues = []
    for l in layers:
        material = ddtt.theidf.getobject('MATERIAL', l)
        mat_rvalues.append(material.rvalue) # appends to the list
    rvalue = film_rvalue + sum(mat_rvalues)

Does that make sense ?

@jamiebull1 used an advanced python structure, that made it hard beginner to read. Specifically, @jamiebull1 used a list generator (The big brother of a list comprehension :-) . @jamiebull1 or myself would be happy to explain if needed.

It is a nice construct. You may find yourself using it often. In fact the list comprehension is used a lot in the eppy tutorial.

**Comment by santoshphilip** [comment]
@ncbrown can you pull up branch `i102_zonesurfaces`and peer review the physics  (and usage) of the r-value, u-value calculation. 

The usage of this would be something like:

    built_up_roof.uvalue
    concrete.uvalue
    concrete.rvalue

It will work for both constructions and materials.
the function is in `eppy/constructions/thermal_properties.py`
the function is added to the `idfobject` in `eppy/bunch_subclass.py` in line `104`

**Comment by MatthewSteen** [comment]
I suggest using `ufactor` over uvalue to follow EnergyPlus usage (also ASHRAE).

**Comment by jamiebull1** [comment]
CIBSE use U value (and R value), but I think consistency with EnergyPlus is probably more important. Is `rfactor` also better?

**Comment by MatthewSteen** [comment]
I have not heard of Rfactor being used. In my experience Ufactor and Uvalue are used interchangeably in the industry. EnergyPlus actually uses both (search results below), but Ufactor is used more frequently and is included in the Envelope Summary report.

[EnergyPlus U-factor](https://github.com/NREL/EnergyPlus/search?utf8=%E2%9C%93&q=u-value)

[EnergyPlus U-value](https://github.com/NREL/EnergyPlus/search?utf8=%E2%9C%93&q=U-value)

**Comment by jamiebull1** [comment]
I think you've mixed up the search results there, but I see that it comes out roughly 10:1 in favour of U-factor which is good enough for me.

**Comment by santoshphilip** [comment]
Thanks @MatthewSteen, @jamiebull1 . 
since eppy is a scripting language for E+, it should use E+ vocabulary 

I'll merge this into the `develop` branch

**Comment by ncbrown** [comment]
My 2 comments:
i see layers being constructed from layers = ddtt.obj[2:]. the construction object has layers starting in the second line; should this be ddtt.obj[1:] instead?
see lines 23 and 42 in thermal_properties.py

Heat capacity is calculated as kJ/m2-K, rather than J/m2-K. Either seems fine with me, but should this get documented somewhere?

**Comment by jamiebull1** [comment]
Thanks for the comments.

1. The `ddtt.obj` is `<type 'list'>: [u'Construction', u'TestConstruction', u'TestMaterial']` in the test with a single layer construction. Index 0 is the EnergyPlus object type and 1 is the name. The layers start from index 2. I've added some more tests to check the calculations for multi-layer constructions.

2. I've added documentation of the units for the three calculations.

**Comment by jamiebull1** [comment]
This is now merged into #102 so I'm closing.

**Pull request closed without merging**
