### PR TITLE
Patch for open file test in `idfreader`

### PR DESCRIPTION
**Pull request by jamiebull1**
This is just a small thing I noticed while looking at how line endings are treated in Eppy. The main point is that in python2 we shouldn't test for `str`, but rather for `basestring` as otherwise there a risk of unicode errors. And given EAFP it's easier to catch the error from trying to open an existing file handle than check for type first.

Also, working on the boy-scout principle I fixed a couple of typos in the docstrings and ran AutoPEP8 while I was there.

### CODE REVIEW

**Comment by santoshphilip** [comment]
Jamie,    I'll review and merge into develop.
You are right about the `str`

Some of eppy's code was written in 2004, when `str` was the only way to do things. I suspect that this kind of code is scattered in many parts of eppy. I have been thinking about how to transition out of it. One strategy is to 
- change all the test files and insert a unicode character that would break when using `str`. 
- Then update the code to fix the failed unit test

**Comment by jamiebull1** [comment]
That would definitely give an indication. It might actually be in conflict with a change to `latin-1` encoding so it would be good to have that settled before accepting PR #73.

**Comment by santoshphilip** [comment]
I have already merged into branch develop.
all tests are passing - in p2 and p3.
We are good for now.

**Comment by santoshphilip** [comment]
Jamie,
Please continue with the `latin-1` solution. I am not going to work on the scattered `str` issue yet. In fact the problem may not even exist. I wouldn't know until I check

**Comment by jamiebull1** [comment]
Ok, sounds good to me. It's ready to merge as far as I'm concerned, unless you have any other thoughts.

Closing this one.

**Pull request merged**
