### PR TITLE
Add encoding option and unit test for IDF.save

### PR DESCRIPTION
**Pull request by jamiebull1**
Ref issue #68

### CODE REVIEW

**Comment by santoshphilip** [comment]
Jamie,
I see that the `save()` has `latin-1` encoding
this should be done for `saveas()` too
One way to do this is to get `saveas()` call `save()` with the new filename

Should you take a look into this ?

**Comment by santoshphilip** [comment]
aha ! on doing a diff with `develop` branch, I see that in `IDF5` you had removed `saveas()` and `savecopy()` functions. If you put them back, `latin-1` encoding will work for them too

**Comment by jamiebull1** [comment]
Not sure how I mixed that up. I assume with the changing numbers of the `IDFx` objects. Anyway, fixed now with tests to cover all parts of the save functions.

**Comment by santoshphilip** [comment]
You can blame the mixup on me.
I was not following PEP-8 in that part of the code.

There was no line spacing between the functions there
When you deleted save(), you also deleted the two functions just below it, since there was no visual separation

**Comment by santoshphilip** [comment]
@jamiebull1 , your function docs are explicit. Are you using a editor that is auto-generating some of this stuff ?

It is putting a little pressure on my coding style (just kidding :-)

**Comment by jamiebull1** [comment]
@santoshphilip No, just used to writing docs in Numpy/Scikits style from my
last couple of projects' coding style so it's become second nature. It may
be overkill but I find it really helpful when working in Eclipse as you can
get the full method signature and description when you're coding. Also you
get useful responses when you call `help(my_object)`.

**Comment by santoshphilip** [comment]
@jamiebull1 ,
some python3 tests are failing

I pulled your branch into
`github.com/santoshphilip/eppy`
see branch `jamiebull1-i68_latin-1-encoding` in `santoshphilip/eppy`

do the following:
    
    # switch to python3    
    cd p3
    py.test # you will run into test failures

One you make updates to python2 code,
Generate the python3 code from python 2 code by:
    
    cd ./eppy/eppy
    sh 2to3sh.sh # this will generate and put the python3 files in ./eppy/p3
    # sh 2to3sh.sh will take about 5 minutes. There are some large files like iddv800.py

**Comment by jamiebull1** [comment]
Ah, OK. I meant to ask how to run 2to3. I'll take a look and fix it.

**Comment by santoshphilip** [comment]
to avoid an unnecessary wait you can convert one file at a time

    cd ./eppy/eppy
    2to3 -Wno ../p3/eppy/ ./modeleditor.py
    2to3 -Wno ../p3/eppy/tests/ ./tests/test_modeleditor.py 
    # I tested this. it should work

**Comment by santoshphilip** [comment]
@eayoungs is working on the streamlining the python2 to python3 conversions and the subsequent packaging for pip install
So this conversion process may change in the future.

**Comment by jamiebull1** [comment]
It seems to be running really quickly for me - maybe 15 seconds or so. Not sure if that means I'm doing something wrong...

**Comment by santoshphilip** [comment]
do a `git status` and see what has changed after running `sh 2to3sh.sh`
Nothing should have changed (if you have not modified any files in python2)

Check date stamps on files in `./eppy/p3/eppy` All the files there should be new

**Comment by jamiebull1** [comment]
Ok, that seems to be working fine now. The solution was opening text files
as binary data for read and write, as I think you're doing elsewhere.

**Comment by santoshphilip** [comment]
merged into develop
all python2 and python3 tests pass

**Comment by jamiebull1** [comment]
Great! By the way, I've just finished setting up the CI so that it automatically runs 2to3sh.sh before running the python 3 tests. That ought to catch things like this.

**Comment by santoshphilip** [comment]
2to3sh.sh takes forever on my laptop (macbook air)
takes no time on my desktop (Mac)
Not sure why :-(

**Comment by jamiebull1** [comment]
There's something odd going on with time taken in the CI branch too. The
Linux python2.7 test takes ages to generate the coverage report while the
3.5 one is really quick. Might be worth looking into reasons.

**Pull request merged**
