### PR TITLE
Paint it black

### PR DESCRIPTION
**Pull request by jamiebull1**
Run `black` on the whole codebase.
Added `black --check .` to the Travis config for Python 3.7 on linux for master and non-master branches, to fail if formatting inconsistencies are found.

### CODE REVIEW

**Comment by santoshphilip** [comment]
@jamiebull1 , I am going to delay this merge by a week - mostly because I am busy, distracted by another project. 
please remind me if nothing happens beyond a week :-)

**Comment by santoshphilip** [comment]
- I had never used black before. I just knew about it. 
- I tried it on a small project I was working on. Very pleased with the results. 
- I am going to go ahead and merge. 

Good call on bringing this into eppy

**Comment by santoshphilip** [comment]
I think I should add a contributor documentation with some steps like:

before pushing to GitHub do the following
- run py.test
- black ./

Do we have any "how to contribute" documentation in eppy ?
A quick look thru did not find any

**Comment by jamiebull1** [comment]
I seem to remember we worked on some contribution documentation before. It probably needs updating, and possibly merging if it never got that far.

**Comment by jamiebull1** [comment]
Here it is #86

**Pull request merged**
