### PR TITLE
i_222 Fix Travis CI on OSX (and bump E+ version to 9.0.1)

### LINKED ISSUE #222: Travis CI builds are failing for Mac
https://travis-ci.org/santoshphilip/eppy/builds/436974919

Looks like issues around changes to default installed version of Python on the test platform.

### PR DESCRIPTION
**Pull request by jamiebull1**
Now that `virtualenv` is no longer available by default on OSX as provided by Travis, we need to install it. We also now manage installation and activation of the python versions to be tested explicitly using `pyenv`.

Finally, took the chance to update to EnergyPlus v9.0.1.

Fixes #222

### CODE REVIEW

**Comment by santoshphilip** [comment]
rolling builds turned on.

**Comment by santoshphilip** [comment]
Should I merge `develop` into `master` and push ?
To make sure the test on master work as expected.

**Comment by jamiebull1** [comment]
Probably a good idea. I tested the build on OSX on my fork, but it's worth checking the full process out - if it's in shape for a release at least.

**Comment by santoshphilip** [comment]
@jamiebull1 , I finally merged `develop` into `master`. it did fail on the mac. Here is the link to it.
https://travis-ci.org/santoshphilip/eppy/builds/522626023

Can you see what is going on.

**Comment by jamiebull1** [comment]
Looks like `virtualenv` on OSX expects a patch version number for Python. I've opened a new PR here https://github.com/santoshphilip/eppy/pull/235

**Pull request merged**
