### PR TITLE
Use output_prefix to determine error filename

### PR DESCRIPTION
**Pull request by tibbe**
When output prefix is set the error filename is <OUTPUT_PREFIX>.err,
not eplusout.err.

### CODE REVIEW

**Comment by tibbe** [comment]
This happens e.g. when you use `runIDFs()` with `output_prefix` set.

**Comment by tibbe** [comment]
Changed base branch to develop.

**Comment by santoshphilip** [comment]
@tibbe , I am having some trouble recreating this error in the `develop` branch (or the `master` branch)

Can you send me a script that will give me this error in the `develop` branch.
Use `idf`, `IDD` and `epw` files from the Energyplus install folder. 
Pick an `idf` file from the `ExampleFiles`  folder. 
That will make it easier for me to recreate the issue

I got a suspicion that there are other issues hiding in this.

**Comment by tibbe** [comment]
You can reproduce the behavior like so:

```
.\energyplus.exe -s D --output-prefix test .\ExampleFiles\1ZoneDataCenterCRAC_wPumpedDXCoolingCoil.idf
```

The error file becomes `test.err`. This happens if you use `runIDFs` and set `output_prefix` in `make_eplaunch_options`.

**Pull request merged**
