### PR TITLE
I62 eplusrunner

### PR DESCRIPTION
**Pull request by jamiebull1**
The integration tests with EnergyPlus are now passing on the CI platforms.

Still to do:
- separate out integration tests from unit tests and define how they should be run
- track the latest version of EnergyPlus in case of breaking changes

### CODE REVIEW

**Comment by jamiebull1** [comment]
@santoshphilip This is back in sync with `develop` and fully unit and integration tested. I've also updated the docs in `newfunctions.rst`.

**Comment by jamiebull1** [comment]
@santoshphilip It would be great if we could get this merged and released at some point. It's been hanging around a long time. Is there anything outstanding that you think it needs?

**Comment by santoshphilip** [comment]
It just dropped off my radar.I'll review and merge.
Santosh

**Comment by santoshphilip** [comment]
I think this is ready for merge into master and a release.
There are two things to check on
- I have to do some documentation work on the runner. I'll use your edits in the new_function.rst file to do this.
    - The edits have to be done in the ipython notebook -> convert to rst file -> make html file
    - I have not documented how this is done. So I can't ask you to do it :-(
- think I ran into trouble running the loopdiagram.py. I'll open an issue on it. Once that is fixed, we can release.

**Pull request merged**
