### PR TITLE
Improve coverage

### PR DESCRIPTION
**Pull request by jamiebull1**
A few changes with the objective of improving test coverage.

### CODE REVIEW

**Comment by jamiebull1** [comment]
@santoshphilip This is failing on several of the tests for `simplesurface.py` on the Python 3 build because of a difference in rounding.

An example:

	E           WALL:EXTERIOR,            
	E               WALL-1PF,                 !- Name
	E               WALL-1,                   !- Construction Name
	E               PLENUM-1,                 !- Zone Name
	E               180.0,                    !- Azimuth Angle
	E               90.0,                     !- Tilt Angle
	E               0,                        !- Starting X Coordinate
	E               0,                        !- Starting Y Coordinate
	E               0,                        !- Starting Z Coordinate
	E               30.5,                     !- Length
	E         -     0.6000000000000001;       !- Height
	E         +     0.6;                      !- Height

I'm not sure where the best place would be to standardise this, or whether in fact we should just refactor the test to use `almost_equal`.

**Comment by santoshphilip** [comment]
Use almost equals. 
I have not found any other way around this problem. 

Santosh.

**Comment by santoshphilip** [comment]
@jamiebull1 are there any places, you would like me to write the tests ?
I am happy to have you do it, if it does smoother that way.

**Comment by jamiebull1** [comment]
@santoshphilip It's actually a really good way for me to get more familiar with what's going on under the hood. Although I feel like I might be missing an easier way of doing things than what I have here for comparing near-equality of `IDF` objects. If you have a few minutes to review it that would be great.

```python
class IDF(object):
	... 
	
	def __almostequal__(self, other, places=7):
		for dtls1, dtls2 in zip(self.model.dtls, other.model.dtls):
			objlst1 = self.model.dt[dtls1]
			objlst2 = other.model.dt[dtls2]
			for obj1, obj2 in zip(objlst1, objlst2):
				for fld1, fld2 in zip(obj1, obj2):
					if not almostequal(fld1, fld2, places):
						return False
		return True

		
def almostequal(first, second, places=7):
	"""docstring for almostequal"""
	# convert to float first
	try:
		first = float(first)
		second = float(second)
	except ValueError:
		# handle non-float types
		return str(first) == str(second)
	# test floats for near-equality
	if round(abs(second-first), places) != 0:
		return False
	else:
		return True
```

**Comment by santoshphilip** [comment]
That would be exactly how I would do it.
You may find it useful to have a almostequal for EpBunch too.
Santosh

**Comment by jamiebull1** [comment]
@santoshphilip I've been taking a look at the [latest coverage report](https://codecov.io/gh/jamiebull1/eppy/tree/00b2aa8451e158fcf860d9cbc8630a00c1ae491e/eppy) and it seems that (apart from the useful scripts folder) a lot of the uncovered code is in `mylib2`, where most of the functions are not used much, if at all in eppy. Because of that I would be reluctant to write any tests for it.

It would be quite helpful if you could let me know what parts of the codebase are more important to be covered, and perhaps what parts can be pruned for the sake of clarity since they're not being used.

**Comment by santoshphilip** [comment]
`mylib2` is code from the days when I first learnt to code in python.
You are welcome to throw out stuff that is not used by `eppy` and test for the remaining.

**Comment by jamiebull1** [comment]
Ok, great. I'm away now until Friday but I'll get the machete out over the weekend and start clearing out the weeds! This coverage improvement is coming along quite nicely though. And it's very satisfying seeing the number creep upwards :-)

**Comment by santoshphilip** [comment]
I am off until Friday too.
I'll be at Ashrae simbuild.
@JasonGlazer is presenting a paper which talks a large scale research project that uses eppy.
(part of the funding for eppy came from this project)

**Comment by jamiebull1** [comment]
Interesting. If it's posted online I'd love to see it. Enjoy!

**Comment by jamiebull1** [comment]
@santoshphilip I'm seeing some strange behaviour in the latest tests. The failure is on `test_get_references`, but when the test is run on its own it passes fine. It looks like it's because the `idd_index` isn't being created when the `idf` is created in the failing test.

Any idea what might be causing this problem?

**Comment by santoshphilip** [comment]
I think I know what the problem is.
I did some hacks in the test code to prevent reading the idd multiple times (takes time to read the idd file). It may be triggered by that.
I am still at the conference. I'll take a look once I am waiting at the airport.

**Comment by santoshphilip** [comment]
Is this in `i87_six` branch ?
I did a `git pull origin i87_six` -> all the tests pass for python2 and python3

**Comment by jamiebull1** [comment]
No it's in a new branch in my repo, `jamiebull1:improve_coverage`

**Comment by santoshphilip** [comment]
OK ... I got that branch.
I'll look thru

**Comment by jamiebull1** [comment]
@santoshphilip I've added an `@pytest.mark.xfail` to the failing test for now so I can keep going on this branch

**Comment by santoshphilip** [comment]
I found the problem. 
It is a bug. I am looking at how to resolve it. 
I think it won't affect any of the other tests.

**Comment by santoshphilip** [comment]
I have fixed the problem in branch `jamiebull1-improve_coverage`
I think it should merge into your code without conflicts.

The problem was the following
    
    IDF.setiddname(args.idd)
    idf = IDF(StringIO("")) # we have an idf.idd_index now
    
    # open another idf file
    idf1 = IDF(StringIO("")) 
        # on the second idf file, idf.idd_index was getting set to {}

Your test was catching this
None of the other tests checked for idd_index

**Comment by jamiebull1** [comment]
@santoshphilip Yes, that's merged fine - everything now passing. And we've just hit the 70% coverage mark thanks to some (hopefully) judicious pruning of `eppy.geometry` and `eppy.EPlusInterfaceFunctions`.

**Comment by JasonGlazer** [comment]
@jamiebull1 Here is the [link ](https://ashrae.org/File%20Library/docLib/Events/Simbuild2016/Papers/C030.pdf)to the SimBuild paper.

**Comment by jamiebull1** [comment]
@JasonGlazer Thanks, that looks really useful - I'm very interested in distributed computing for EnergyPlus at the moment. Looks like you might have found the `idf.run()` function #101 useful too if we'd got it completed earlier!

**Comment by JasonGlazer** [comment]
@jamiebull1 yes that would have been great to have.

**Comment by jamiebull1** [comment]
@santoshphilip I think this is ready to go into `i87_six` now, and potentially then `i87_six` into `develop`. The test coverage is now pretty high (77.5%) and we're testing it all cross-platform and cross-version. I've been fairly brutal, so there may be things that have been removed that some people use (though mainly in if people are dipping into `mylib1` or `mylib2` - which they shouldn't really be). I haven't touched what I think of as the public-facing API though.

Is there any way you can think of to recruit users to test their scripts against this version so we can see if there are any features/functions I've pruned that should have been left alone?

And I guess more generally, what's your point of view on breaking backwards compatibility at this stage?

Anyway, it should be a lot easier to get new developers up to speed now though with much better test coverage. I'm certainly only using this branch to develop against for things I need in my doctorate (primarily geometry editing at the moment), since it seems a lot clearer now, and I know quickly if I've broken something.

**Comment by jamiebull1** [comment]
It's a real shame we never managed to get this merged in. I put a lot of work into it, and it's now pretty much unsalvageable using the normal tools.

I'll take another look at it over the next few days though and see what I can recover manually.

**Pull request closed without merging**
