### PR TITLE
[WIP] i116_improve_coverage into develop

### PR DESCRIPTION
**Pull request by jamiebull1**
Work in progress, trying to recover the progress made on improving test coverage.

### CODE REVIEW

**Comment by santoshphilip** [comment]
Sorry I let this slip - and didn't get it merged in time :-(

**Comment by jamiebull1** [comment]
I'll try and keep on top of it and keep it up to date with the `develop` branch. I took my eye off the ball too and it got too far behind. It may be better to come at it with fresh eyes, and also involve you a bit more too rather than dumping a massive change set on you.

**Comment by jamiebull1** [comment]
And in that spirit, where do you see as most useful to build up the coverage?

Is there anything in here that can definitely be removed as it's not used any more? I don't want to waste time writing unit tests for orphaned code if I can help it. I seem to recall `mylib1` and `mylib2` aren't actually used, is that right? What about `simplesurface`

Also, are the `useful_scripts` really useful scripts? If so they would be much more useful if they were better tested like with `loopdiagram`.

    ---------- coverage: platform win32, python 2.7.13-final-0 -----------
    Name                                         Stmts   Miss  Cover
    ----------------------------------------------------------------
    cleanup.py                                      29     29     0%
    eppy\EPlusInterfaceFunctions\eplusdata.py      159     70    56%
    eppy\EPlusInterfaceFunctions\iddgroups.py      111      8    93%
    eppy\EPlusInterfaceFunctions\mylib1.py          21     13    38%
    eppy\EPlusInterfaceFunctions\mylib2.py         227    200    12%
    eppy\EPlusInterfaceFunctions\parse_idd.py      236     77    67%
    eppy\EPlusInterfaceFunctions\readidf.py         51     25    51%
    eppy\bunch_subclass.py                         278      7    97%
    eppy\bunchhelpers.py                            45     12    73%
    eppy\constructions\thermal_properties.py        87      6    93%
    eppy\ex_inits.py                                13     13     0%
    eppy\function_helpers.py                        57     15    74%
    eppy\geometry\height_surface.py                 38     38     0%
    eppy\geometry\int2lines.py                      37     37     0%
    eppy\geometry\mcve.py                           11     11     0%
    eppy\geometry\surface.py                        77      4    95%
    eppy\hvacbuilder.py                            746    272    64%
    eppy\iddgaps.py                                 93      1    99%
    eppy\idf_msequence.py                           39      5    87%
    eppy\idfreader.py                              125     21    83%
    eppy\loops.py                                  136      9    93%
    eppy\modeleditor.py                            458     26    94%
    eppy\pytest_helpers.py                          22      4    82%
    eppy\results\readhtml.py                       125     13    90%
    eppy\runner\run_functions.py                   101     13    87%
    eppy\simpleread.py                              71     19    73%
    eppy\simplesurface.py                          277    277     0%
    eppy\useful_scripts\autosize.py                 26     26     0%
    eppy\useful_scripts\change_edges.py             24     24     0%
    eppy\useful_scripts\doc_images.py               10     10     0%
    eppy\useful_scripts\eppy_version.py             15     15     0%
    eppy\useful_scripts\eppyreadtest_file.py        38     38     0%
    eppy\useful_scripts\eppyreadtest_folder.py      40     40     0%
    eppy\useful_scripts\idfdiff.py                 135    135     0%
    eppy\useful_scripts\idfdiff_missing.py         130    130     0%
    eppy\useful_scripts\loopdiagram.py             316     63    80%
    eppy\useful_scripts\renamecolon.py              58     58     0%
    eppy\walk_hvac.py                               53     53     0%
    eppy\walls_functions3.py                        18     18     0%
    eppy\walls_functions4.py                        17     17     0%
    openfile.py                                     14     14     0%
    setup.py                                        27     27     0%
    ----------------------------------------------------------------
    TOTAL                                         4717   1893    60%

**Comment by santoshphilip** [comment]
I shall go in and do some slash and burn. I think I know what can be removed.

**Comment by santoshphilip** [comment]
I created a new branch `i116_slashandburn`:

- removed all kinds of random files
- mylib2.py is gone
- mylib1.py has some functions that are used in the older code. We keep it
- simplesurface.py is gone

There is some useful stuff -> http://pythonhosted.org/eppy/useful_scripts.html
I am mulling making a separate repository of this. Would make it easier for others to contribute.
Let us leave this alone for the moment.

Not seeing much more that I can clean up.

**Comment by jamiebull1** [comment]
Nice one. I'll take a look.

I like the idea of a useful scripts repo too. I do use them from time to time so I know there's some good stuff in there.

**Comment by santoshphilip** [comment]
This has been merged into develop

**Pull request closed without merging**
