### PR TITLE
Update the true azimuth calculation

### PR DESCRIPTION
**Pull request by airallergy**
Add consideration of `GlobalGeometryRules` to address #292

### CODE REVIEW

**Comment by airallergy** [comment]
Still working on the the bit in `test_bunch_subclass`.

**Comment by airallergy** [comment]
`Absolute` is no longer an alias for `World` in terms of the coordination system in v9.3.0. A version check can be easy to implement, but I think it would not hurt to just leave it for now, and see what would happen in the future ep releases.

**Comment by santoshphilip** [comment]
You can check the `idd` from the `idfobject` to see what values are available to `Coordinate_System`
run the code snippets below (uncomment print statements to make it more verbose)

code snippet 1 (change the version number to an E+ version you have installed)

    idftxt = """Version,8.9;

    GlobalGeometryRules,
        UpperLeftCorner,         !- Starting Vertex Position
        CounterClockWise,        !- Vertex Entry Direction
        World;                   !- Coordinate System
    """

    import eppy
    from io import StringIO
    idf = eppy.openidf(StringIO(idftxt))
    grules = idf.idfobjects['GlobalGeometryRules'][0]
    # print("-" * 8)
    # print(grules.objidd)
    # print("-" * 8)
    # print(grules.fieldnames)
    # print("-" * 8)
    index = grules.fieldnames.index('Coordinate_System')
    grules.objidd[index]
    print(grules.objidd[3]['key'])
    # print("-" * 8)


Code snippet 2

    idftxt = """Version,9.3;

    GlobalGeometryRules,
        UpperLeftCorner,         !- Starting Vertex Position
        CounterClockWise,        !- Vertex Entry Direction
        World;                   !- Coordinate System
    """

    import eppy
    from io import StringIO
    idf = eppy.openidf(StringIO(idftxt))
    grules = idf.idfobjects['GlobalGeometryRules'][0]
    # print("-" * 8)
    # print(grules.objidd)
    # print("-" * 8)
    # print(grules.fieldnames)
    # print("-" * 8)
    index = grules.fieldnames.index('Coordinate_System')
    grules.objidd[index]
    print(grules.objidd[3]['key'])
    # print("-" * 8)

**Comment by airallergy** [comment]
You are right, this clearly looks like a more robust way to do the trick.

One possible issue though, I noticed that `eppy` does not care about the possible mismatch between the idd version and the idf version field. Say I set the idd to an 8.0.0 one, while the version specified in the idf is 9.3.0, `eppy` will still process. I am not sure how `eppy` handled this deep down, this seems to affect the available objects and fields to parse. But I could not think of a case of field changes to check. Any thoughts?

**Comment by santoshphilip** [comment]
eppy does not check. It assumes that you know what you are doing.

I can see a use case fo this:
- open an idf9 in a version 9.0 with idd set to 9.0
- open an idf8 snippet in version 8.0 
    - this will be opened using idd=9.0
    - this may or may not break depending on the objects in idf8
- copy object from idf8 to idf9 
- use idf9 to continue your work

**Comment by airallergy** [comment]
This is a good point, and leads to my another question, why `eppy` only allows one idd to be set?

Although value checking should not be an essential here as we discussed before, idd file is different I think, for a wrong idd file could potentially mess up with the idf parsing, like dropping important objects or fields.

took a quick look at the `modeleditor.py`, I can see that setting idd is designed as a class method, I am wondering why not just an instance method and one can do

```python
idf1 = IDF()
idf1.setiddname("eppy/resources/iddfiles/Energy+V8_8_0.idd")

idf2 = IDF()
idf2.setiddname("eppy/resources/iddfiles/Energy+V8_9_0.idd")
```

from there, something like cross-instance copy can address the use case.

**Comment by airallergy** [comment]
ok... a quick search in issues, I came across this one #49, and the explanation there makes perfect sense. Btw, I am totally amazed that the journey started back in 2004.

I am wondering if restructuring the idd functionality is still on your to-do list? if yes, I can see that dropping python 2 is a great opportunity to do this. Although I am still quite infant in programming, I can certainly help if you need any.

**Comment by santoshphilip** [comment]
IDD files may be a dead end. E+ works with JSON files
See this issue #137 

Also see https://github.com/pyenergyplus/eppy3000.
it is like eppy, but works with JSON files.
It also interoperates with eppy - meaning, you can use eppy files witihin eppy3000.
Eppy3000 is a work in progress. At the moment I am the only one working it. I don't think anyone knows of it's existence.

**Comment by airallergy** [comment]
I am aware of the json transition, by `idd` I suppose I can say that I was referring to the same role that idd and jdd serve. Also I do know about `eppy3000`, I even know what 3000 means :) haven't taken a close look into it though.

**Comment by santoshphilip** [comment]
@airallergy ,  I have been thinking thru this.


`eppy` is a stable, established software.
in `eppy` there are the following options
- Look at the open issues. 
    - You may want to work on one of them
- Open an issue that think needs attention 


The other option is to work on `eppy3000`

Couple of points about working on eppy3000
- You will be getting involved at a very early stage of the project
    - The things to deal with are very different.
    - You will play a role in the design of the software
    - you may get an understanding of how to manage an open source project
- `eppy3000` has to happen one way or the other, because of the IDD format will be retired. (It is already retired within the E+ modeling engine)
- you are taking a risk, since this is not a established software yet.


Hard to say which is the best pathway. The only way is to try either of both.

**Comment by airallergy** [comment]
@santoshphilip, sorry for the late reply, I was quite occupied for the last few weeks. thank you for pointing out these options, I would say that potential challenges in eppy3000 sounds more intriguing to me :) but I am also willing to help fix some issues in the current eppy since there is still some time before eppy3000 can be fully functional I suppose. I will take a look around and see what I can do.

**Comment by santoshphilip** [comment]
@airallergy, eppy3000 may be progressing quicker than anticipated. There are a recent conference call on the next editor. There were about 20 people on the call. Many interesting issues were raised

This call was triggered by an invite that was put in the energyplus yahoo group

    If you use IDF Editor and would like to help prioritize the 
    features on a new cross platform editor focused on the new 
    epJSON format being developed, please let me know when you 
    will be available for a conference call:

    https://doodle.com/poll/r8ne2qshc6nczuuu

    Thanks

    Jason

    -- 
    Jason Glazer, P.E., BEMP, GARD Analytics, 90.1 ECB chair
    Admin for onebuilding.org building performance mailing lists



    ------------------------------------
    Posted by: Jason Glazer <jglazer@gard.com>
    ------------------------------------

    EnergyPlus support is found at:
    http://energyplus.helpserve.com or send a message to energyplus-support@gard.com

    The EnergyPlus web site is found at:
    http://www.energyplus.net/

    The group web site is:
    http://groups.yahoo.com/group/EnergyPlus_Support/

In a separate email, I suggested to Jason that he use eppy3000 to build the editor. He is open to the idea and said he will take a look at eppy3000. As a background to this, the original eppy was partially written to support a large scale project that Jason was working on.

In any case this motivated me restart the work on eppy3000.  I am actively opening issues and resolving them. If you look at the closed issues, you can see the progress.

**Comment by airallergy** [comment]
@santoshphilip, I get to have a quick look at the `eppy3000` codes and have some tiny thoughts.

1. the minimum python version.
I saw that the minimum is currently 3.4 stated on pypi, I suppose this is no longer appropriate. I'm not sure if you have had some thoughts on it yourself, I would say 3.6 would be good, one benefit from my experience (might not be entirely true) is that some quite useful functionalities of pathlib starts from 3.6, and 3.6 seems neither too old to be expectedly alive for long, nor too new to be widely used.

2. open()
I saw a few cases that use `open()` without a `with ... as` statement or a following `close()`, I suppose this could be not safe, and could drag down the performance since those schema files are quite large.

**Comment by santoshphilip** [comment]
Can you open issues for both. We can pick it up from there.

**Comment by santoshphilip** [comment]
I have updated the tutorial here:
https://eppy3000.readthedocs.io/en/latest/

I am recreating the tutorial in eppy as a way of finding gaps in the eppy3000 API and finding errors in the code.
Where I find issues, I just put t TODO in the documentation as a way of getting back to it later.

Some of the tutorial has nothing to do with eppy, but deals with eppy3000 specific stuff.

This may be good place for you to take a look. 
As an interesting note, eppy was documentation driven. As we wrote the documentation we found that the code/API had to change. There were things we wanted to do in the tutorial that we could not do unless we changed the code :-)

**Pull request merged**
